


namespace VTABLE {
    enum {
		RESET = 16,
		ENDSCENE = 42,
		RESETEX = 132,
		ALLOCATEKEYVALUESMEMORY = 2,
		CREATEMOVE = 22,
		FRAMESTAGENOTIFY = 37,
		PAINTTRAVERSE = 41,
		OVERRIDEVIEW = 18,
		GETVIEWMODELFOV = 35,
		DOPOSTSCREENEFFECTS = 44,
		DRAWMODELEXECUTE = 21,
		DRAWMODEL = 29,
		RENDERSMOKEOVERLAY = 41,
		ISCONNECTED = 27,
		LISTLEAVESINBOX = 6,
		RUNCOMMAND = 19,
		SENDMESSAGE = 0,
		RETRIEVEMESSAGE = 2,
		EMITSOUND = 5,
		OVERRIDECONFIG = 21,
		SCENEEND = 9,
		LOCKCURSOR = 67,
		PLAYSOUND = 82,
		FIREEVENT = 9,
		GETBOOL = 13,
		SENDNETMSG = 40,
		SENDDATAGRAM = 46
    }
}